Adding Memory Handler Class, Singleton currently doesnt compile due to undefined reference to the MemoryHandler Pointer. Not sure yet why this doesnt work